#pragma checksum "..\..\frm_ExportWarehousingMaterials.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "061063EAFA25FD0D9D3819D9A45FEE35"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DSofT.Framework.Metro.UIControls;
using DSofT.Framework.UIControl;
using DSofT.Framework.UICore;
using DSofT.Warehouse.Resources;
using DevExpress.Mvvm;
using DevExpress.Mvvm.UI;
using DevExpress.Mvvm.UI.Interactivity;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using DevExpress.Xpf.NavBar;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DSofT.Warehouse.UI {
    
    
    /// <summary>
    /// frm_ExportWarehousingMaterials
    /// </summary>
    public partial class frm_ExportWarehousingMaterials : DSofT.Framework.UICore.ControlBase, System.Windows.Markup.IComponentConnector {
        
        
        #line 28 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Mvvm.UI.NotificationService notificationService;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BrdBtnWrap;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnNew;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSearch;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnExcel;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.NavBar.NavBarControl nbcSearch;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.NavBar.NavBarGroup cbgSearch;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.NavBar.NavBarItem cbiSearch;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Selection_Area;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFromDate;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.DateEdit dtpFromDate;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblToDate;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.DateEdit dtpToDate;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Body_Area;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grd;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\frm_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView grdView;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DSofT.Warehouse.UI;component/frm_exportwarehousingmaterials.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\frm_ExportWarehousingMaterials.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.notificationService = ((DevExpress.Mvvm.UI.NotificationService)(target));
            return;
            case 2:
            this.BrdBtnWrap = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.btnNew = ((System.Windows.Controls.Button)(target));
            
            #line 45 "..\..\frm_ExportWarehousingMaterials.xaml"
            this.btnNew.Click += new System.Windows.RoutedEventHandler(this.btnNew_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnSearch = ((System.Windows.Controls.Button)(target));
            
            #line 46 "..\..\frm_ExportWarehousingMaterials.xaml"
            this.btnSearch.Click += new System.Windows.RoutedEventHandler(this.btnSearch_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btnExcel = ((System.Windows.Controls.Button)(target));
            
            #line 47 "..\..\frm_ExportWarehousingMaterials.xaml"
            this.btnExcel.Click += new System.Windows.RoutedEventHandler(this.btnExcel_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.nbcSearch = ((DevExpress.Xpf.NavBar.NavBarControl)(target));
            return;
            case 7:
            this.cbgSearch = ((DevExpress.Xpf.NavBar.NavBarGroup)(target));
            return;
            case 8:
            this.cbiSearch = ((DevExpress.Xpf.NavBar.NavBarItem)(target));
            return;
            case 9:
            this.Selection_Area = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this.lblFromDate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.dtpFromDate = ((DevExpress.Xpf.Editors.DateEdit)(target));
            return;
            case 12:
            this.lblToDate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.dtpToDate = ((DevExpress.Xpf.Editors.DateEdit)(target));
            return;
            case 14:
            this.Body_Area = ((System.Windows.Controls.Grid)(target));
            return;
            case 15:
            this.grd = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 16:
            this.grdView = ((DevExpress.Xpf.Grid.TableView)(target));
            
            #line 81 "..\..\frm_ExportWarehousingMaterials.xaml"
            this.grdView.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.grdView_MouseDown);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

