#pragma checksum "..\..\popupFood.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "46406508F5F4A71F56BF8D1038EA7DF5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DSofT.Framework.Metro.UIControls;
using DSofT.Framework.UIControl;
using DSofT.Framework.UICore;
using DSofT.Warehouse.Resources;
using DevExpress.Mvvm;
using DevExpress.Mvvm.UI;
using DevExpress.Mvvm.UI.Interactivity;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using DevExpress.Xpf.NavBar;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DSofT.Warehouse.UI {
    
    
    /// <summary>
    /// popupFood
    /// </summary>
    public partial class popupFood : DSofT.Framework.UICore.PopupBase, System.Windows.Markup.IComponentConnector {
        
        
        #line 28 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Mvvm.UI.NotificationService notificationService;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BrdBtnWrap;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnNew;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDelete;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.NavBar.NavBarControl nbcSearch;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.NavBar.NavBarGroup cbgSearch;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.NavBar.NavBarItem cbiSearch;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Selection_Area;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFoodCode;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit txtFoodCode;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFoodName;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit txtFoodName;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFoodType;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ComboBoxEdit cboFoodType;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblRemark;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit txtRemark;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblListMaterial;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grd_Material;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\popupFood.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView tblMaterial;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DSofT.Warehouse.UI;component/popupfood.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\popupFood.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.notificationService = ((DevExpress.Mvvm.UI.NotificationService)(target));
            return;
            case 2:
            this.BrdBtnWrap = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.btnNew = ((System.Windows.Controls.Button)(target));
            
            #line 46 "..\..\popupFood.xaml"
            this.btnNew.Click += new System.Windows.RoutedEventHandler(this.btnNew_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 47 "..\..\popupFood.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.btnSave_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btnDelete = ((System.Windows.Controls.Button)(target));
            
            #line 48 "..\..\popupFood.xaml"
            this.btnDelete.Click += new System.Windows.RoutedEventHandler(this.btnDelete_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 49 "..\..\popupFood.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.btnClose_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.nbcSearch = ((DevExpress.Xpf.NavBar.NavBarControl)(target));
            return;
            case 8:
            this.cbgSearch = ((DevExpress.Xpf.NavBar.NavBarGroup)(target));
            return;
            case 9:
            this.cbiSearch = ((DevExpress.Xpf.NavBar.NavBarItem)(target));
            return;
            case 10:
            this.Selection_Area = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.lblFoodCode = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.txtFoodCode = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 13:
            this.lblFoodName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.txtFoodName = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 15:
            this.lblFoodType = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.cboFoodType = ((DevExpress.Xpf.Editors.ComboBoxEdit)(target));
            return;
            case 17:
            this.lblRemark = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.txtRemark = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 19:
            this.lblListMaterial = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.grd_Material = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 21:
            this.tblMaterial = ((DevExpress.Xpf.Grid.TableView)(target));
            
            #line 91 "..\..\popupFood.xaml"
            this.tblMaterial.CellValueChanging += new DevExpress.Xpf.Grid.CellValueChangedEventHandler(this.tblMaterial_CellValueChanging);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

