//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSofT.Warehouse.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSofT.Warehouse.Domain.Resources.FormResources", typeof(FormResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng.
        /// </summary>
        public static string Error_EmailAddressDVS {
            get {
                return ResourceManager.GetString("Error_EmailAddressDVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có độ dài tối đa {1} ký tự.
        /// </summary>
        public static string Error_MaxLength {
            get {
                return ResourceManager.GetString("Error_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không đúng định dạng.
        /// </summary>
        public static string Error_PhoneNumberDVS {
            get {
                return ResourceManager.GetString("Error_PhoneNumberDVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập {0}.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập {0}.
        /// </summary>
        public static string Error_RequiredIfDVS {
            get {
                return ResourceManager.GetString("Error_RequiredIfDVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn {0}.
        /// </summary>
        public static string Error_RequiredIfSelectDVS {
            get {
                return ResourceManager.GetString("Error_RequiredIfSelectDVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn {0}.
        /// </summary>
        public static string Error_RequiredSelect {
            get {
                return ResourceManager.GetString("Error_RequiredSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có độ dài tối đa {1} ký tự.
        /// </summary>
        public static string Error_StringLength {
            get {
                return ResourceManager.GetString("Error_StringLength", resourceCulture);
            }
        }
    }
}
