#pragma checksum "..\..\popup_ExportWarehousingMaterials.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "EC78CA1599ADA23460A2F7D0C1607970"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DSofT.Framework.UIControl;
using DSofT.Framework.UICore;
using DSofT.Warehouse.Resources;
using DevExpress.Mvvm;
using DevExpress.Mvvm.UI;
using DevExpress.Mvvm.UI.Interactivity;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using DevExpress.Xpf.NavBar;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DSofT.Warehouse.UI {
    
    
    /// <summary>
    /// popup_ExportWarehousingMaterials
    /// </summary>
    public partial class popup_ExportWarehousingMaterials : DSofT.Framework.UICore.PopupBase, System.Windows.Markup.IComponentConnector {
        
        
        #line 28 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Mvvm.UI.NotificationService notificationService;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BrdBtnWrap;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.NavBar.NavBarControl nbcInfor;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.NavBar.NavBarGroup cbgInfor;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.NavBar.NavBarItem cbiInfor;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Selection_Area;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblSchools;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ComboBoxEdit cboSchool;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblWarehousingMaterialsCode;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit txtWarehousingMaterialsCode;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblImplementationDates;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.DateEdit dtpImplementationDates;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkIsConfirm;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblWarehouseId;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ComboBoxEdit cboWarehouseId;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblWarehouseIdTo;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ComboBoxEdit cboWarehouseIdTo;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox gbDetail;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAdd;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDelete;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.GridControl grd;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\popup_ExportWarehousingMaterials.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Grid.TableView grdView;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DSofT.Warehouse.UI;component/popup_exportwarehousingmaterials.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\popup_ExportWarehousingMaterials.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.notificationService = ((DevExpress.Mvvm.UI.NotificationService)(target));
            return;
            case 2:
            this.BrdBtnWrap = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 45 "..\..\popup_ExportWarehousingMaterials.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.btnSave_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 46 "..\..\popup_ExportWarehousingMaterials.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.btnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.nbcInfor = ((DevExpress.Xpf.NavBar.NavBarControl)(target));
            return;
            case 6:
            this.cbgInfor = ((DevExpress.Xpf.NavBar.NavBarGroup)(target));
            return;
            case 7:
            this.cbiInfor = ((DevExpress.Xpf.NavBar.NavBarItem)(target));
            return;
            case 8:
            this.Selection_Area = ((System.Windows.Controls.Grid)(target));
            return;
            case 9:
            this.lblSchools = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.cboSchool = ((DevExpress.Xpf.Editors.ComboBoxEdit)(target));
            
            #line 74 "..\..\popup_ExportWarehousingMaterials.xaml"
            this.cboSchool.EditValueChanged += new DevExpress.Xpf.Editors.EditValueChangedEventHandler(this.cboSchool_EditValueChanged);
            
            #line default
            #line hidden
            return;
            case 11:
            this.lblWarehousingMaterialsCode = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.txtWarehousingMaterialsCode = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 13:
            this.lblImplementationDates = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.dtpImplementationDates = ((DevExpress.Xpf.Editors.DateEdit)(target));
            
            #line 79 "..\..\popup_ExportWarehousingMaterials.xaml"
            this.dtpImplementationDates.EditValueChanged += new DevExpress.Xpf.Editors.EditValueChangedEventHandler(this.dtpImplementationDates_EditValueChanged);
            
            #line default
            #line hidden
            return;
            case 15:
            this.chkIsConfirm = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 16:
            this.lblWarehouseId = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.cboWarehouseId = ((DevExpress.Xpf.Editors.ComboBoxEdit)(target));
            
            #line 83 "..\..\popup_ExportWarehousingMaterials.xaml"
            this.cboWarehouseId.EditValueChanged += new DevExpress.Xpf.Editors.EditValueChangedEventHandler(this.cboWarehouseId_EditValueChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.lblWarehouseIdTo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.cboWarehouseIdTo = ((DevExpress.Xpf.Editors.ComboBoxEdit)(target));
            return;
            case 20:
            this.gbDetail = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 21:
            this.btnAdd = ((System.Windows.Controls.Button)(target));
            
            #line 99 "..\..\popup_ExportWarehousingMaterials.xaml"
            this.btnAdd.Click += new System.Windows.RoutedEventHandler(this.btnAddRow_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.btnDelete = ((System.Windows.Controls.Button)(target));
            
            #line 100 "..\..\popup_ExportWarehousingMaterials.xaml"
            this.btnDelete.Click += new System.Windows.RoutedEventHandler(this.btnDeleteRow_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.grd = ((DevExpress.Xpf.Grid.GridControl)(target));
            return;
            case 24:
            this.grdView = ((DevExpress.Xpf.Grid.TableView)(target));
            
            #line 104 "..\..\popup_ExportWarehousingMaterials.xaml"
            this.grdView.CellValueChanged += new DevExpress.Xpf.Grid.CellValueChangedEventHandler(this.grdView_CellValueChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

